trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: echo "Pipeline started"
  displayName: Start

- task: NodeTool@1
  inputs:
    versionSpec: '18.x'

- script: npm install
  displayName: Install dependencies

- script: docker --version
  displayName: Check Docker

- script: docker build -t ecom-app .
  displayName: Build Docker Image
  