trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: echo "Pipeline started"
  displayName: Start

- task: NodeTool@1
  inputs:
    versionSpec: '18.x'

- script: npm install
  displayName: Install dependencies

- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository:'swaroopgrf/ecom-devops'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest